name = "JuliaUnregisteredPackage2"
uuid = "a3862d4b-0ac1-4ed1-8cfe-80e674e65fe5"
version = "0.1.0"

[deps]
JuliaUnregisteredPackage1 = "27edc75c-098c-4eeb-a6e0-526f84666e38"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[sources.JuliaUnregisteredPackage1]
rev = "main"
url = "https://github.com/gboulmier/JuliaUnregisteredPackage1"
